/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 steak.gltf --transform -t
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    steak: THREE.Mesh
  }
  materials: {
    steakMaterial: THREE.MeshStandardMaterial
  }
}

export function SteakMesh(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    './assets/burger/steak-transformed.glb'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.steak.geometry}
        material={materials.steakMaterial}
      />
    </group>
  )
}

useGLTF.preload('./assets/burger/steak-transformed.glb')
