/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 topBun.gltf --transform -t
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    Object_8_1: THREE.Mesh
    Object_8_2: THREE.Mesh
  }
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
  }
}

export function TopBunMesh(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    './assets/burger/topBun-transformed.glb'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials['Material.006']}
      />
      <mesh
        geometry={nodes.Object_8_1.geometry}
        material={materials['Material.010']}
      />
      <mesh
        geometry={nodes.Object_8_2.geometry}
        material={materials['Material.008']}
      />
    </group>
  )
}

useGLTF.preload('./assets/burger/topBun-transformed.glb')
